// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance_minor, currency, status, version, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.BalanceMinor,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (
    id, owner, balance_minor, currency, status, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAccountParams struct {
	ID           uuid.UUID
	Owner        string
	BalanceMinor int64
	Currency     string
	Status       string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Owner,
		arg.BalanceMinor,
		arg.Currency,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance_minor, currency, status, version, created_at, updated_at
FROM accounts
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.BalanceMinor,
			&i.Currency,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :execrows
UPDATE accounts
SET balance_minor = $2,
    status        = $3,
    updated_at    = $4,
    version       = version + 1
WHERE id = $1
  AND version = $5
`

type UpdateAccountParams struct {
	ID           uuid.UUID
	BalanceMinor int64
	Status       string
	UpdatedAt    time.Time
	Version      int64
}

// UpdateAccount is the optimistic-lock write: it only matches while the row is
// still at the version we loaded, and returns the affected row count so the
// repository can turn 0 into entity.ErrConflict.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccount,
		arg.ID,
		arg.BalanceMinor,
		arg.Status,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
