// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID
	Owner        string
	BalanceMinor int64
	Currency     string
	Status       string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Post struct {
	ID        uuid.UUID
	Name      string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	IssuedAt  time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
