// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPersons = `-- name: CountPersons :one
SELECT count(*)
FROM persons
WHERE user_id = $1
  AND NOT is_self
  AND (
      $2::text IS NULL
      OR full_name ILIKE '%' || $2 || '%'
      OR organization ILIKE '%' || $2 || '%'
  )
`

type CountPersonsParams struct {
	UserID uuid.UUID
	Search pgtype.Text
}

// CountPersons exists so a paginated response can report a total. It repeats
// ListPersons' predicate deliberately: the two must agree, and a count that
// quietly filters differently is worse than no count at all.
func (q *Queries) CountPersons(ctx context.Context, arg CountPersonsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPersons, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePerson = `-- name: DeletePerson :execrows
DELETE FROM persons
WHERE id = $1
  AND user_id = $2
  AND NOT is_self
`

type DeletePersonParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// DeletePerson is a hard delete (PLAN D7): the row's relationships and their
// interactions go with it by cascade, and anyone introduced through this person
// keeps their history with met_through_person_id set to null.
//
// The self person is excluded. Deleting it would strip the user of the node
// every one of their relationships runs from, and the partial unique index
// means registration cannot simply recreate it.
func (q *Queries) DeletePerson(ctx context.Context, arg DeletePersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerson, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPerson = `-- name: GetPerson :one
SELECT id, user_id, is_self, full_name, email, phone, occupation,
       organization, location, notes, version, created_at, updated_at
FROM persons
WHERE id = $1
  AND user_id = $2
`

type GetPersonParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPerson(ctx context.Context, arg GetPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, arg.ID, arg.UserID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsSelf,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Occupation,
		&i.Organization,
		&i.Location,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelfPerson = `-- name: GetSelfPerson :one
SELECT id, user_id, is_self, full_name, email, phone, occupation,
       organization, location, notes, version, created_at, updated_at
FROM persons
WHERE user_id = $1
  AND is_self
`

// GetSelfPerson loads the user's own node in the graph. Every MVP relationship
// runs from this row (PLAN D1), so the relationship use cases resolve it on
// create rather than trusting a from_person_id off the request body.
func (q *Queries) GetSelfPerson(ctx context.Context, userID uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getSelfPerson, userID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsSelf,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Occupation,
		&i.Organization,
		&i.Location,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :exec

INSERT INTO persons (
    id, user_id, is_self, full_name, email, phone, occupation,
    organization, location, notes, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type InsertPersonParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	IsSelf       bool
	FullName     string
	Email        pgtype.Text
	Phone        pgtype.Text
	Occupation   pgtype.Text
	Organization pgtype.Text
	Location     pgtype.Text
	Notes        pgtype.Text
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Every statement in this file is scoped by user_id, without exception. That is
// PLAN D3: ownership is enforced here rather than in the handler, so a use case
// that forgets a check gets "not found" instead of another user's data. A query
// added below without a user_id predicate is a security bug, not a style slip.
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.Exec(ctx, insertPerson,
		arg.ID,
		arg.UserID,
		arg.IsSelf,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Occupation,
		arg.Organization,
		arg.Location,
		arg.Notes,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPersons = `-- name: ListPersons :many
SELECT id, user_id, is_self, full_name, email, phone, occupation,
       organization, location, notes, version, created_at, updated_at
FROM persons
WHERE user_id = $1
  AND NOT is_self
  AND (
      $2::text IS NULL
      OR full_name ILIKE '%' || $2 || '%'
      OR organization ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListPersonsParams struct {
	UserID uuid.UUID
	Search pgtype.Text
	Offset int32
	Limit  int32
}

// ListPersons is both the list and the search endpoint, as one query with an
// optional term (PLAN M2). ILIKE '%...%' is served by the trigram indexes on
// full_name and organization (PLAN D8), which is why the term is matched with a
// substring pattern rather than a prefix.
//
// The self person is excluded: it is the user's own node, not someone they
// know, and leaving it in puts every user in their own contact list and makes
// the people count off by one. GetSelfPerson is how that row is reached.
func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersons,
		arg.UserID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsSelf,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Occupation,
			&i.Organization,
			&i.Location,
			&i.Notes,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET full_name    = $3,
    email        = $4,
    phone        = $5,
    occupation   = $6,
    organization = $7,
    location     = $8,
    notes        = $9,
    updated_at   = $10,
    version      = version + 1
WHERE id = $1
  AND user_id = $2
  AND version = $11
RETURNING version
`

type UpdatePersonParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	FullName     string
	Email        pgtype.Text
	Phone        pgtype.Text
	Occupation   pgtype.Text
	Organization pgtype.Text
	Location     pgtype.Text
	Notes        pgtype.Text
	UpdatedAt    time.Time
	Version      int64
}

// UpdatePerson is the optimistic-lock write: it only matches while the row is
// still at the version we loaded. It returns the version it assigned, so the
// caller can report the current one rather than the stale one it wrote with; no
// row coming back is what the repository turns into entity.ErrConflict.
//
// user_id and is_self are not in the SET list. Ownership and the identity of
// the self node are not editable facts, so there is no statement here that can
// change them.
func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (int64, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Occupation,
		arg.Organization,
		arg.Location,
		arg.Notes,
		arg.UpdatedAt,
		arg.Version,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
