// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPost = `-- name: GetPost :one
SELECT id, name, version, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :exec
INSERT INTO posts (
    id, name, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertPostParams struct {
	ID        uuid.UUID
	Name      string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.Exec(ctx, insertPost,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPosts = `-- name: ListPosts :many
SELECT id, name, version, created_at, updated_at
FROM posts
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE posts
SET name       = $2,
    updated_at = $3,
    version    = version + 1
WHERE id = $1
  AND version = $4
`

type UpdatePostParams struct {
	ID        uuid.UUID
	Name      string
	UpdatedAt time.Time
	Version   int64
}

// UpdatePost is the optimistic-lock write: it only matches while the row is
// still at the version we loaded, and returns the affected row count so the
// repository can turn 0 into entity.ErrConflict.
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Name,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
