// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	// GetSessionByTokenHash filters on expiry in the query as well as in the
	// aggregate. Doing it here means an expired session cannot be loaded at all,
	// which keeps a bug in a future caller from turning into an authentication
	// bypass; the aggregate's own check then covers the row that expires between
	// this read and that check.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertPost(ctx context.Context, arg InsertPostParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	// UpdateAccount is the optimistic-lock write: it only matches while the row is
	// still at the version we loaded, and returns the affected row count so the
	// repository can turn 0 into entity.ErrConflict.
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error)
	// UpdatePost is the optimistic-lock write: it only matches while the row is
	// still at the version we loaded, and returns the affected row count so the
	// repository can turn 0 into entity.ErrConflict.
	UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error)
	// UpdateUser is the optimistic-lock write: it only matches while the row is
	// still at the version we loaded, and returns the affected row count so the
	// repository can turn 0 into entity.ErrConflict.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
