// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, email, name, password_hash, role, version, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, version, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    id, email, name, password_hash, role, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertUserParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET name          = $2,
    password_hash = $3,
    updated_at    = $4,
    version       = version + 1
WHERE id = $1
  AND version = $5
`

type UpdateUserParams struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
	UpdatedAt    time.Time
	Version      int64
}

// UpdateUser is the optimistic-lock write: it only matches while the row is
// still at the version we loaded, and returns the affected row count so the
// repository can turn 0 into entity.ErrConflict.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
