// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/kethaka-creskit/go-ddd-service/config"
	"github.com/kethaka-creskit/go-ddd-service/internal/application"
	"github.com/kethaka-creskit/go-ddd-service/internal/domain/account/entity"
	entity3 "github.com/kethaka-creskit/go-ddd-service/internal/domain/auth/entity"
	entity2 "github.com/kethaka-creskit/go-ddd-service/internal/domain/post/entity"
	"github.com/kethaka-creskit/go-ddd-service/internal/infrastructure/persistence"
	"github.com/kethaka-creskit/go-ddd-service/internal/infrastructure/security"
	"github.com/kethaka-creskit/go-ddd-service/internal/infrastructure/system"
	"github.com/kethaka-creskit/go-ddd-service/internal/interfaces/rest"
	"github.com/kethaka-creskit/go-ddd-service/internal/interfaces/rest/account"
	"github.com/kethaka-creskit/go-ddd-service/internal/interfaces/rest/auth"
	"github.com/kethaka-creskit/go-ddd-service/internal/interfaces/rest/post"
	"github.com/kethaka-creskit/go-ddd-service/pkg/httpserver"
	"github.com/kethaka-creskit/go-ddd-service/pkg/logger"
	"github.com/kethaka-creskit/go-ddd-service/pkg/postgres"
)

// Injectors from wire.go:

// InitializeAPI builds the whole service, opening its own pool.
func InitializeAPI(ctx context.Context, cfg *config.Config) (*API, error) {
	pool, err := postgres.New(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(pool)
	sessionRepository := persistence.NewSessionRepository(pool)
	txManager := persistence.NewTxManager(pool)
	clock := system.NewClock()
	idGenerator := system.NewIDGenerator()
	hasher := security.NewHasher()
	tokenGenerator := security.NewTokenGenerator()
	sessionTTL := provideSessionTTL(cfg)
	slogLogger := logger.New(cfg)
	authService := application.NewAuthService(userRepository, sessionRepository, txManager, clock, idGenerator, hasher, tokenGenerator, sessionTTL, slogLogger)
	cookieConfig := provideCookieConfig(cfg)
	handler := auth.NewHandler(authService, cookieConfig, slogLogger)
	accountRepository := persistence.NewAccountRepository(pool)
	accountService := application.NewAccountService(accountRepository, txManager, clock, idGenerator, slogLogger)
	accountHandler := account.NewHandler(accountService, slogLogger)
	postRepository := persistence.NewPostRepository(pool)
	postService := application.NewPostService(postRepository, txManager, clock, idGenerator, slogLogger)
	postHandler := post.NewHandler(postService, slogLogger)
	httpHandler := rest.NewRouter(cfg, handler, accountHandler, postHandler, pool, slogLogger)
	server := httpserver.New(cfg, httpHandler)
	api := &API{
		Server:  server,
		Handler: httpHandler,
		Pool:    pool,
		Log:     slogLogger,
	}
	return api, nil
}

// InitializeAPIWithPool builds the service on a caller-supplied pool.
func InitializeAPIWithPool(cfg *config.Config, pool *pgxpool.Pool) *API {
	userRepository := persistence.NewUserRepository(pool)
	sessionRepository := persistence.NewSessionRepository(pool)
	txManager := persistence.NewTxManager(pool)
	clock := system.NewClock()
	idGenerator := system.NewIDGenerator()
	hasher := security.NewHasher()
	tokenGenerator := security.NewTokenGenerator()
	sessionTTL := provideSessionTTL(cfg)
	slogLogger := logger.New(cfg)
	authService := application.NewAuthService(userRepository, sessionRepository, txManager, clock, idGenerator, hasher, tokenGenerator, sessionTTL, slogLogger)
	cookieConfig := provideCookieConfig(cfg)
	handler := auth.NewHandler(authService, cookieConfig, slogLogger)
	accountRepository := persistence.NewAccountRepository(pool)
	accountService := application.NewAccountService(accountRepository, txManager, clock, idGenerator, slogLogger)
	accountHandler := account.NewHandler(accountService, slogLogger)
	postRepository := persistence.NewPostRepository(pool)
	postService := application.NewPostService(postRepository, txManager, clock, idGenerator, slogLogger)
	postHandler := post.NewHandler(postService, slogLogger)
	httpHandler := rest.NewRouter(cfg, handler, accountHandler, postHandler, pool, slogLogger)
	server := httpserver.New(cfg, httpHandler)
	api := &API{
		Server:  server,
		Handler: httpHandler,
		Pool:    pool,
		Log:     slogLogger,
	}
	return api
}

// wire.go:

// coreSet is everything above the database: it takes a *pgxpool.Pool as given.
// Splitting the graph here is what lets the integration tests reuse the exact
// production wiring against a throwaway container pool, instead of maintaining
// a second, subtly different graph.
var coreSet = wire.NewSet(logger.New, persistence.NewAccountRepository, persistence.NewPostRepository, persistence.NewUserRepository, persistence.NewSessionRepository, persistence.NewTxManager, system.NewClock, system.NewIDGenerator, security.NewHasher, security.NewTokenGenerator, provideSessionTTL,
	provideCookieConfig, application.NewAccountService, application.NewPostService, application.NewAuthService, account.NewHandler, post.NewHandler, auth.NewHandler, rest.NewRouter, httpserver.New, wire.Struct(new(API), "*"), wire.Bind(new(entity.Repository), new(*persistence.AccountRepository)), wire.Bind(new(entity2.Repository), new(*persistence.PostRepository)), wire.Bind(new(application.TxManager), new(*persistence.TxManager)), wire.Bind(new(application.Clock), new(system.Clock)), wire.Bind(new(application.IDGenerator), new(system.IDGenerator)), wire.Bind(new(account.Service), new(*application.AccountService)), wire.Bind(new(post.Service), new(*application.PostService)), wire.Bind(new(entity3.UserRepository), new(*persistence.UserRepository)), wire.Bind(new(entity3.SessionRepository), new(*persistence.SessionRepository)), wire.Bind(new(application.PasswordHasher), new(*security.Hasher)), wire.Bind(new(application.TokenGenerator), new(security.TokenGenerator)), wire.Bind(new(auth.Service), new(*application.AuthService)),
)
